spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Victor357
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# Ambiente
app.ambiente=${EFEN_AMBIENTE}
app.jwt-secret=Tc!@321
app.empresa=TCIA
app.nome-sistema=${EFEN_NOME_SISTEMA}
app.url-site=${EFEN_URL_SITE}
app.url-front-end=${EFEN_URL_FRONT_END}
app.diretorio-bkp=${EFEN_DIRETORIO_BKP}
app.qtd-processamentos=${EFEN_QTD_PROCESSAMENTOS}

# Server Configurations
server.port=${EFEN_APP_PORT}
server.servlet.context-path=${EFEN_APP_CONTEXT_PATH}
server.servlet.encoding.charset=UTF-8

# Spring Application Configuration
spring.application.name=${EFEN_APP_NAME}

# Spring Servlet Multipart
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


# Flyway Configuration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

# Mail Configuration
spring.mail.host=${EFEN_MAIL_HOST}
spring.mail.port=${EFEN_MAIL_PORT}
spring.mail.username=${EFEN_MAIL_USERNAME}
spring.mail.password=${EFEN_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true







